### PR TITLE
feat: tmq replace VALUE_DESERIALIZER with VALUE_CLASS, and add VALUE_…

### PR DESCRIPTION
**Pull request by gepengjun**
tmq replace VALUE_DESERIALIZER with VALUE_CLASS, and add VALUE_MAP_UNDER_SCORE_TO_CAMEL_CASE

### CODE REVIEW

**Comment by gepengjun** [comment]
replace value.class with value.deserializer, so we don't not need to define an empty deserializer class.
add value.mapUnderscoreToCamelCase to auto map the field name which is camel case with the column name which is under score

**Comment by huolibo** [comment]
Users can realize `V deserialize(ResultSet data)` method by themselves if necessary. They will not be limited by a given implementation such as `ReferenceDeserializer`.

**Comment by gepengjun** [comment]
i think in most mq products, we need different deserializer because we can define the serializer. but in the tmq, we have to  deserialize from the ResultSet, in fact the sql we used when we define the topic. of course,  you think users can define  their desrializer, it is right

**Comment by huolibo** [comment]
I think converting the ResultSet to CamelCase format is also a requirement, so you are welcome to submit a deserializer sometime

**Pull request closed without merging**
